### ISSUE TITLE
Add dynamic Day and Time in Weather Output

### ISSUE THREAD

**Issue by piyushkhurana2019** [piyushkhurana2019/PK-Temperatures#1]
Make this Red Part Dynamic
<img width="1440" alt="Screenshot 2023-06-04 at 11 01 43 PM" src="https://github.com/piyushkhurana2019/PK-Temperatures/assets/96003210/056a4ee9-3459-4c35-b6ee-ca58cfef34d0">

**Comment by sachin3145** [comment]
I am willing to work on this issue, please assign it to me.

**Comment by piyushkhurana2019** [comment]
> I am willing to work on this issue, please assign it to me.

ok @sachin3145 you can work on it
